/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdminWorkArea;

import Business.Address.Address;
import Business.Employee.Employee;
import Business.Hospital.Hospital;
import Business.Network;
import Business.Organization.Organization;
import Business.Role.AdminRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class ManageHospitalAdminJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Network network;

    /**
     * Creates new form ManageEnterpriseJPanel
     */
    public ManageHospitalAdminJPanel(JPanel userProcessContainer, Business.Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.network = network;
        populateTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        networkJComboBox = new javax.swing.JComboBox();
        enterpriseTypeJComboBox = new javax.swing.JComboBox();
        nameJTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        hospitallist_jTable = new javax.swing.JTable();
        submitJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        usernameJTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        hospitalName_jText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        passwordJPasswordField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        adminnameJTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        networkJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        networkJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkJComboBoxActionPerformed(evt);
            }
        });

        enterpriseTypeJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Network");

        jLabel3.setText("Enterprise Type");

        jLabel2.setText("Name");

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hospitallist_jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Hospital Name", "Address", "Zip Code", "Contact Number", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        hospitallist_jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hospitallist_jTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(hospitallist_jTable);
        if (hospitallist_jTable.getColumnModel().getColumnCount() > 0) {
            hospitallist_jTable.getColumnModel().getColumn(0).setResizable(false);
            hospitallist_jTable.getColumnModel().getColumn(1).setResizable(false);
            hospitallist_jTable.getColumnModel().getColumn(2).setResizable(false);
            hospitallist_jTable.getColumnModel().getColumn(3).setResizable(false);
            hospitallist_jTable.getColumnModel().getColumn(4).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 85, 953, 95));

        submitJButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        submitJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/16/Knob-Valid-Green-icon.png"))); // NOI18N
        submitJButton.setText("Submit");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        add(submitJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(978, 373, 137, -1));

        backJButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        backJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/16/Knob-Fast-Rewind-icon.png"))); // NOI18N
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 373, 130, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Admin Username");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 279, 130, -1));
        add(usernameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 273, 175, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Hospital Name");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 205, 98, -1));

        hospitalName_jText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalName_jTextActionPerformed(evt);
            }
        });
        add(hospitalName_jText, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 199, 175, -1));

        jLabel4.setFont(new java.awt.Font("Cambria", 3, 36)); // NOI18N
        jLabel4.setText("Create Hospital Admin Dashboard");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Password");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 317, 130, -1));
        add(passwordJPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 311, 175, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Admin Name");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 240, -1, -1));
        add(adminnameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 237, 175, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/watermark_1.PNG"))); // NOI18N
        jLabel6.setText("jLabel6");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        String username = usernameJTextField.getText();
        String password = String.valueOf(passwordJPasswordField.getText());
        String name = adminnameJTextField.getText();
        int selectedRow = hospitallist_jTable.getSelectedRow();
        if (selectedRow >= 0) {
            if (username.equals("") || password.equals("") || name.equals("")) {
                JOptionPane.showMessageDialog(null, "Please fill all details");
            } else {
                Hospital hospital = (Hospital) hospitallist_jTable.getValueAt(selectedRow, 4);
                Organization adminOrganization = hospital.getOrganizationDirectory().createOrganization(Organization.Type.Admin);
                Employee employee = network.getEmployeeDirectory().createEmployee(name);
                UserAccount account = adminOrganization.getUserAccountDirectory().createUserAccount(username, password, employee, new AdminRole());
                JOptionPane.showMessageDialog(null, "Admin successfully created", "Warning", JOptionPane.WARNING_MESSAGE);
                hospitalName_jText.setText("");
                adminnameJTextField.setText("");
                passwordJPasswordField.setText("");
                usernameJTextField.setText("");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a hospital", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.remove(this);
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void networkJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_networkJComboBoxActionPerformed

    private void hospitalName_jTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitalName_jTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hospitalName_jTextActionPerformed

    private void hospitallist_jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hospitallist_jTableMouseClicked
        int row = hospitallist_jTable.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Hospital hospital = (Hospital) hospitallist_jTable.getValueAt(row, 4);
        hospitalName_jText.setText(hospital.getHospitalName());
        // TODO add your handling code here:
    }//GEN-LAST:event_hospitallist_jTableMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adminnameJTextField;
    private javax.swing.JButton backJButton;
    private javax.swing.JComboBox enterpriseTypeJComboBox;
    private javax.swing.JTextField hospitalName_jText;
    private javax.swing.JTable hospitallist_jTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JComboBox networkJComboBox;
    private javax.swing.JTextField passwordJPasswordField;
    private javax.swing.JButton submitJButton;
    private javax.swing.JTextField usernameJTextField;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        int rowCount = hospitallist_jTable.getRowCount();
        DefaultTableModel model = (DefaultTableModel) hospitallist_jTable.getModel();
        for (int i = 0; i < rowCount; i++) {
            model.removeRow(i);
        }
        for (Hospital hospital : network.getHospitalDirectory().getHospitalDirectory()) {
            Object[] row = new Object[5];
            row[0] = hospital.getHospitalName();
            row[1] = hospital.getAddress();
            row[2] = hospital.getAddress().getZipCode();
            row[3] = hospital.getHospitalcontactNumber();
            row[4] = hospital;
            model.addRow(row);
        }
    }
}
