/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdminWorkArea;

import Business.Network;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author barua
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private Network network;
    public SystemAdminWorkAreaJPanel(JPanel userProcessContainer, Network network) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.network=network;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnManageHospitalAuthentication = new javax.swing.JButton();
        btnManageHospital1 = new javax.swing.JButton();
        updateHospitalDetailsButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cambria", 3, 36)); // NOI18N
        jLabel1.setText("SYSTEM ADMINSTRATOR DASHBOARD");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 630, -1));

        btnManageHospitalAuthentication.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnManageHospitalAuthentication.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/32/Knob-Favorite-icon.png"))); // NOI18N
        btnManageHospitalAuthentication.setText("Manage Hospital Authentication");
        btnManageHospitalAuthentication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageHospitalAuthenticationActionPerformed(evt);
            }
        });
        add(btnManageHospitalAuthentication, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 271, 319, 48));

        btnManageHospital1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnManageHospital1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/32/Knob-Forward-icon.png"))); // NOI18N
        btnManageHospital1.setText("Manage Hospital");
        btnManageHospital1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageHospital1ActionPerformed(evt);
            }
        });
        add(btnManageHospital1, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 175, 319, 51));

        updateHospitalDetailsButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        updateHospitalDetailsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/32/Knob-Favorite-icon.png"))); // NOI18N
        updateHospitalDetailsButton.setText("Update Hospital Details");
        updateHospitalDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateHospitalDetailsButtonActionPerformed(evt);
            }
        });
        add(updateHospitalDetailsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 364, 319, 48));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/watermark_1.PNG"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 620));
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageHospitalAuthenticationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageHospitalAuthenticationActionPerformed
        ManageHospitalAdminJPanel manageHospitalAdminJPanel=new ManageHospitalAdminJPanel(userProcessContainer, network);
        userProcessContainer.add("ManageHospitalAdminJPanel",manageHospitalAdminJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageHospitalAuthenticationActionPerformed

    private void btnManageHospital1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageHospital1ActionPerformed
        ManageHospitalJPanel manageHospitalJPanel=new ManageHospitalJPanel(userProcessContainer, network);
        userProcessContainer.add("ManageNetworkJPanel",manageHospitalJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageHospital1ActionPerformed

    private void updateHospitalDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateHospitalDetailsButtonActionPerformed
        // TODO add your handling code here:
        UpdateHospitalJPanel updateHospitalJPanel=new UpdateHospitalJPanel(userProcessContainer, network);
        userProcessContainer.add("UpdateHospitalJPanel",updateHospitalJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_updateHospitalDetailsButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageHospital1;
    private javax.swing.JButton btnManageHospitalAuthentication;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton updateHospitalDetailsButton;
    // End of variables declaration//GEN-END:variables
}
