/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdministrativeRole;

import Business.Employee.Employee;
import Business.Hospital.Hospital;
import Business.Network;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author barua
 */
public class ManageUserAccountJPanel extends javax.swing.JPanel {

    private OrganizationDirectory directory;
    private JPanel userProcessContainer;
    private Network network;
    private Hospital hospital;

    /**
     * Creates new form ManageUserAccountJPanel
     */
    public ManageUserAccountJPanel(JPanel userProcessContainer, Network network, Hospital hospital) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.network = network;
        this.hospital = hospital;
        this.directory = hospital.getOrganizationDirectory();
        populateOrganizationComboBox();
        populateData();
    }

    public void populateOrganizationComboBox() {
        organizationJComboBox.removeAllItems();

        for (Organization organization : hospital.getOrganizationDirectory().getOrganizationDirectory()) {
            organizationJComboBox.addItem(organization);
//            populateEmployeeComboBox(organization);
//            populateRoleComboBox(organization);
        }
    }

    public void populateEmployeeComboBox(Organization organization) {
        employeeJComboBox.removeAllItems();

        for (Employee employee : organization.getEmployeeDirectory().getEmployeeList()) {
            employeeJComboBox.addItem(employee);
        }
    }

    private void populateRoleComboBox(Organization organization) {
        roleJComboBox.removeAllItems();
        for (Role role : organization.getSupportedRole()) {
            roleJComboBox.addItem(role);
        }
    }

    public void populateData() {

        DefaultTableModel model = (DefaultTableModel) userJTable.getModel();

        model.setRowCount(0);

        for (Organization organization : hospital.getOrganizationDirectory().getOrganizationDirectory()) {
            for (UserAccount ua : organization.getUserAccountDirectory().getUserAccountDirectory()) {
                Object row[] = new Object[2];
                row[0] = ua.getUserName();
                row[1] = ua.getRole();
                ((DefaultTableModel) userJTable.getModel()).addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        userJTable = new javax.swing.JTable();
        nameJTextField = new javax.swing.JTextField();
        passwordJTextField = new javax.swing.JTextField();
        organizationJLabe = new javax.swing.JLabel();
        employeeJLabel = new javax.swing.JLabel();
        roleJLabel = new javax.swing.JLabel();
        roleJLabel1 = new javax.swing.JLabel();
        roleJLabel2 = new javax.swing.JLabel();
        createJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        organizationJComboBox = new javax.swing.JComboBox();
        employeeJComboBox = new javax.swing.JComboBox();
        roleJComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "User Name", "Role"
            }
        ));
        jScrollPane1.setViewportView(userJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 69, 540, 220));
        add(nameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 444, 169, -1));
        add(passwordJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 483, 169, -1));

        organizationJLabe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        organizationJLabe.setText("Organization");
        add(organizationJLabe, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 326, 84, 20));

        employeeJLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        employeeJLabel.setText("Employee");
        add(employeeJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 365, 84, 20));

        roleJLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        roleJLabel.setText("Role");
        add(roleJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 404, 84, 20));

        roleJLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        roleJLabel1.setText("Username");
        add(roleJLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 443, 84, 20));

        roleJLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        roleJLabel2.setText("Password");
        add(roleJLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 482, 84, 20));

        createJButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        createJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/16/Knob-Play-Green-icon.png"))); // NOI18N
        createJButton.setText("Create");
        createJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createJButtonActionPerformed(evt);
            }
        });
        add(createJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 532, -1, -1));

        backJButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        backJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/16/Knob-Fast-Rewind-icon.png"))); // NOI18N
        backJButton.setText(" Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 532, -1, -1));

        organizationJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        organizationJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizationJComboBoxActionPerformed(evt);
            }
        });
        add(organizationJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 327, 169, -1));

        employeeJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        employeeJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeJComboBoxActionPerformed(evt);
            }
        });
        add(employeeJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 366, 169, -1));

        roleJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(roleJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 405, 169, -1));

        jLabel1.setFont(new java.awt.Font("Cambria", 3, 36)); // NOI18N
        jLabel1.setText("Manage User Account");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 11, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/watermark_1.PNG"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void createJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createJButtonActionPerformed
        // TODO add your handling code here:
        String userName = nameJTextField.getText();
        String password = passwordJTextField.getText();
        if (userName.equals("") || password.equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill all details");
        } else {
            Organization organization = (Organization) organizationJComboBox.getSelectedItem();
            Employee employee = (Employee) employeeJComboBox.getSelectedItem();
            Role role = (Role) roleJComboBox.getSelectedItem();

            organization.getUserAccountDirectory().createUserAccount(userName, password, employee, role);

            populateData();
            nameJTextField.setText("");
            passwordJTextField.setText("");
            JOptionPane.showMessageDialog(null, "User Id has been created for employee");
        }
    }//GEN-LAST:event_createJButtonActionPerformed

    private void employeeJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeJComboBoxActionPerformed

    private void organizationJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizationJComboBoxActionPerformed
        // TODO add your handling code here:
        Organization selectedOrganization = (Organization) organizationJComboBox.getSelectedItem();
        if (selectedOrganization != null) {
            populateEmployeeComboBox(selectedOrganization);
            populateRoleComboBox(selectedOrganization);
        }
    }//GEN-LAST:event_organizationJComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton createJButton;
    private javax.swing.JComboBox employeeJComboBox;
    private javax.swing.JLabel employeeJLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JComboBox organizationJComboBox;
    private javax.swing.JLabel organizationJLabe;
    private javax.swing.JTextField passwordJTextField;
    private javax.swing.JComboBox roleJComboBox;
    private javax.swing.JLabel roleJLabel;
    private javax.swing.JLabel roleJLabel1;
    private javax.swing.JLabel roleJLabel2;
    private javax.swing.JTable userJTable;
    // End of variables declaration//GEN-END:variables
}
