/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdministrativeRole;

import Business.Connection.HospitalConnection;
import Business.Hospital.BloodDetails;
import UserInterface.User.*;
import Business.Hospital.Hospital;
import Business.Network;
import Business.Organization.Organization;
import Business.User.User;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author barua
 */
public class SearchBloodFromHospitals extends javax.swing.JPanel {

    /**
     * Creates new form SearchBloodBank
     */
    private JPanel userProcessContainer;
    private Network network;
    private Hospital hospital;
    private Organization organization;

    public SearchBloodFromHospitals(JPanel userProcessContainer, Network network, Organization organization, Hospital hospital) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.network = network;
        this.hospital = hospital;
        this.organization = organization;
        populateComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bloodGroupComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        hospitalzip_jTable = new javax.swing.JTable();
        contactHospital_jButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bloodGroupComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        bloodGroupComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bloodGroupComboBoxMouseClicked(evt);
            }
        });
        add(bloodGroupComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 119, 152, -1));

        jLabel1.setText("Blood Group :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 122, 104, -1));

        hospitalzip_jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Hospital Name", "Hospital Address", "Hospital Email ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(hospitalzip_jTable);
        if (hospitalzip_jTable.getColumnModel().getColumnCount() > 0) {
            hospitalzip_jTable.getColumnModel().getColumn(0).setResizable(false);
            hospitalzip_jTable.getColumnModel().getColumn(1).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 169, 903, 166));

        contactHospital_jButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        contactHospital_jButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/16/Knob-Forward-icon.png"))); // NOI18N
        contactHospital_jButton.setText("Send Request To Hospital");
        contactHospital_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactHospital_jButtonActionPerformed(evt);
            }
        });
        add(contactHospital_jButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(788, 353, 202, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/16/Knob-Fast-Rewind-icon.png"))); // NOI18N
        jButton1.setText(" Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 353, -1, -1));

        searchButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/16/Knob-Search-icon.png"))); // NOI18N
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 117, 110, -1));

        jLabel3.setFont(new java.awt.Font("Cambria", 3, 36)); // NOI18N
        jLabel3.setText("Search Blood in Another Hospital");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 37, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/watermark_1.PNG"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 630));
    }// </editor-fold>//GEN-END:initComponents

    private void contactHospital_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactHospital_jButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = hospitalzip_jTable.getSelectedRow();
        if (selectedRow >= 0) {
            Hospital selectedHospital = (Hospital) hospitalzip_jTable.getValueAt(selectedRow, 2);
            HospitalConnection hospitalConnection = network.getHospitalConnectionDirectory().addHospitalConnection();
            hospitalConnection.setSenderHospital(hospital);
            hospitalConnection.setReceiverHospital(selectedHospital);
            hospitalConnection.setBloodGroup((String) bloodGroupComboBox.getSelectedItem());
            hospitalConnection.setConnectionStatus("Request Received");
            hospitalConnection.setApprovedBy(null);
            JOptionPane.showMessageDialog(null, "Request has been sent to the "+ selectedHospital.getHospitalName()+ " Hospital " );
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row");
        }
    }//GEN-LAST:event_contactHospital_jButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.remove(this);
        layout.previous(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bloodGroupComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bloodGroupComboBoxMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bloodGroupComboBoxMouseClicked

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) hospitalzip_jTable.getModel();
        model.setRowCount(0);
        String selectedBloodGroup = (String) bloodGroupComboBox.getSelectedItem();
        for (Hospital innerhospital : network.getHospitalDirectory().getHospitalDirectory()) {
            for (BloodDetails bloodDetails : innerhospital.getInventory().getBloodDetailsDirectory().getBloodDetailsDirectory()) {
                if (!(innerhospital.getHospitalemailId().equals(hospital.getHospitalemailId()))) {
                    if (selectedBloodGroup.equals(bloodDetails.getBloodGroup()) && hospital.getAddress().getCity().equalsIgnoreCase(innerhospital.getAddress().getCity())) {
                        Object row[] = new Object[model.getColumnCount()];
                        row[0] = innerhospital.getHospitalName();
                        row[1] = innerhospital.getAddress();
                        row[2] = innerhospital;
                        model.addRow(row);
                        break;
                    } else {
                        continue;
                    }
                }
            }
        }
    }//GEN-LAST:event_searchButtonActionPerformed
    private void populateComboBox() {
        bloodGroupComboBox.removeAllItems();
        bloodGroupComboBox.addItem("O+ve");
        bloodGroupComboBox.addItem("O-ve");
        bloodGroupComboBox.addItem("A+ve");
        bloodGroupComboBox.addItem("A-ve");
        bloodGroupComboBox.addItem("B+ve");
        bloodGroupComboBox.addItem("B-ve");
        bloodGroupComboBox.addItem("AB+ve");
        bloodGroupComboBox.addItem("AB-ve");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox bloodGroupComboBox;
    private javax.swing.JButton contactHospital_jButton;
    private javax.swing.JTable hospitalzip_jTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchButton;
    // End of variables declaration//GEN-END:variables

}
