/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.ConfigureBusiness;
import Business.DB4OUtil.DB4OUtil;
import Business.Hospital.Hospital;
import Business.Hospital.HospitalDirectory;
import Business.Network;
import Business.Organization.AdminOrganization;
import Business.Organization.DoctorOrganization;
import Business.Organization.LabOrganization;
import Business.Organization.Organization;
import Business.User.User;
import Business.UserAccount.UserAccount;
import UserInterface.AdministrativeRole.AdminWorkAreaJPanel;
import UserInterface.DoctorRole.DoctorWorkAreaJPanel;
import UserInterface.LabAssitant.LabAssitantWorkAreaJPanel;
import UserInterface.SystemAdminWorkArea.ManageHospitalJPanel;
import UserInterface.SystemAdminWorkArea.SystemAdminWorkAreaJPanel;
import UserInterface.User.RegisterUser;
import UserInterface.User.UserHomePage;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author barua
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    private Network network;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();

    public LoginPage() {
        initComponents();
        network = dB4OUtil.retrieveSystem();
        //network = ConfigureBusiness.configure();
        logoutButton.setEnabled(false);
        logoutButton.setVisible(false);
        userIdTextField.setVisible(true);
        passwordTextField.setVisible(true);
        loginButton.setVisible(true);
        jLabel1.setVisible(true);
        jLabel2.setVisible(true);
        registerUserButton.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        HeaderJPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userIdTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        registerUserButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        passwordTextField = new javax.swing.JPasswordField();
        userProcessContainer = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerLocation(100);
        jSplitPane1.setDividerSize(1);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        HeaderJPanel.setBackground(new java.awt.Color(159, 0, 0));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel1.setText("User ID");

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel2.setText("Password");

        loginButton.setBackground(new java.awt.Color(255, 255, 255));
        loginButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        loginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/16/Knob-Forward-icon.png"))); // NOI18N
        loginButton.setText("Login");
        loginButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        registerUserButton.setBackground(new java.awt.Color(255, 255, 255));
        registerUserButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        registerUserButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/16/Knob-Forward-icon.png"))); // NOI18N
        registerUserButton.setText(" New User : Register");
        registerUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerUserButtonActionPerformed(evt);
            }
        });

        logoutButton.setBackground(new java.awt.Color(255, 255, 255));
        logoutButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        logoutButton.setText("Log Out");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        passwordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HeaderJPanelLayout = new javax.swing.GroupLayout(HeaderJPanel);
        HeaderJPanel.setLayout(HeaderJPanelLayout);
        HeaderJPanelLayout.setHorizontalGroup(
            HeaderJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderJPanelLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(userIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(loginButton)
                .addGap(41, 41, 41)
                .addComponent(registerUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 230, Short.MAX_VALUE)
                .addComponent(logoutButton)
                .addGap(67, 67, 67))
        );
        HeaderJPanelLayout.setVerticalGroup(
            HeaderJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderJPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(HeaderJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(userIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(loginButton)
                    .addComponent(registerUserButton)
                    .addComponent(logoutButton)
                    .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86))
        );

        jSplitPane1.setTopComponent(HeaderJPanel);

        userProcessContainer.setBackground(new java.awt.Color(255, 255, 255));
        userProcessContainer.setLayout(new java.awt.CardLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/loginPage.png"))); // NOI18N
        userProcessContainer.add(jLabel3, "card2");

        jSplitPane1.setRightComponent(userProcessContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerUserButtonActionPerformed
        // TODO add your handling code here:
        //HeaderJPanel.setVisible(false);
        RegisterUser registerUserPanel = new RegisterUser(userProcessContainer, network);
        userProcessContainer.add("registerUserPanel", registerUserPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_registerUserButtonActionPerformed

    public void setVisibility() {
        userIdTextField.setEnabled(false);
        passwordTextField.setEnabled(false);
        loginButton.setEnabled(false);
        logoutButton.setVisible(true);
        registerUserButton.setEnabled(false);
        logoutButton.setEnabled(true);

        userIdTextField.setVisible(false);
        passwordTextField.setVisible(false);
        loginButton.setVisible(false);
        registerUserButton.setVisible(false);
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
    }
    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        try {
            User user;
            UserAccount userAccount;
            Organization organization = null;
            Hospital hospital = null;
            user = network.getUserDirectory().authenticateUser(userIdTextField.getText(), passwordTextField.getText());
            if (user != null) {
                setVisibility();
                UserHomePage userHomePage = new UserHomePage(userProcessContainer, network, user);
                userProcessContainer.add("userHomePage", userHomePage);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            } else {
                userAccount = network.getUserAccountDirectory().authenticateUser(userIdTextField.getText(), passwordTextField.getText());
                if (userAccount != null) {
                    setVisibility();
                    SystemAdminWorkAreaJPanel systemadminJPanel = new SystemAdminWorkAreaJPanel(userProcessContainer, network);
                    userProcessContainer.add("SystemAdminWorkAreaJPanel", systemadminJPanel);
                    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                    layout.next(userProcessContainer);
                } else {
                    outerloop:
                    for (Hospital innerhospital : network.getHospitalDirectory().getHospitalDirectory()) {
                        for (Organization innerorganization : innerhospital.getOrganizationDirectory().getOrganizationDirectory()) {
                            UserAccount inneruserAccount = innerorganization.getUserAccountDirectory().authenticateUser(userIdTextField.getText(), passwordTextField.getText());
                            if (inneruserAccount != null) {
                                organization = innerorganization;
                                hospital = innerhospital;
                                userAccount = inneruserAccount;
                            }
                        }
                    }

                    if (userAccount == null) {
                        JOptionPane.showMessageDialog(null, "Please eneter correct user id or password");
                    }

                    if (organization instanceof AdminOrganization) {
                        setVisibility();
                        AdminWorkAreaJPanel adminWorkAreaJPanel = new AdminWorkAreaJPanel(userProcessContainer, network, organization, hospital, userAccount);
                        userProcessContainer.add("adminWorkAreaJPanel", adminWorkAreaJPanel);
                        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                        layout.next(userProcessContainer);
                    }
                    if (organization instanceof DoctorOrganization) {
                        setVisibility();
                        DoctorWorkAreaJPanel doctorWorkAreaJPanel = new DoctorWorkAreaJPanel(userProcessContainer, userAccount, (DoctorOrganization) organization, network, hospital);
                        userProcessContainer.add("doctorWorkAreaJPanel", doctorWorkAreaJPanel);
                        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                        layout.next(userProcessContainer);
                    }
                    if (organization instanceof LabOrganization) {
                        setVisibility();
                        LabAssitantWorkAreaJPanel labAssitantWorkAreaJPanel = new LabAssitantWorkAreaJPanel(userProcessContainer, network, organization, userAccount, hospital);
                        userProcessContainer.add("LabAssitantWorkAreaJPanel", labAssitantWorkAreaJPanel);
                        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                        layout.next(userProcessContainer);
                    }
                }
            }

            userIdTextField.setText("");
            passwordTextField.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please enter correct email id or passsowrd");
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        userIdTextField.setEnabled(true);
        userIdTextField.setVisible(true);
        passwordTextField.setEnabled(true);
        loginButton.setEnabled(true);
        registerUserButton.setEnabled(true);

        userIdTextField.setVisible(true);
        passwordTextField.setVisible(true);
        logoutButton.setVisible(false);
        registerUserButton.setVisible(true);
        loginButton.setVisible(true);
        jLabel1.setVisible(true);
        jLabel2.setVisible(true);
        userProcessContainer.removeAll();
        JPanel blankJP = new JPanel();
        blankJP.setBackground(Color.white);
        ImageIcon icon = new ImageIcon("C:\\Users\\barua\\Desktop\\Final AED\\x-dev_final_project\\Blood Bank Supply Chain System\\src\\Images\\loginPage.png");
        JLabel thumb = new JLabel();
        thumb.setIcon(icon);
        blankJP.add(thumb);
        userProcessContainer.add("blank", blankJP);
        CardLayout crdLyt = (CardLayout) userProcessContainer.getLayout();
        crdLyt.next(userProcessContainer);
        dB4OUtil.storeSystem(network);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void passwordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HeaderJPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton loginButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JButton registerUserButton;
    private javax.swing.JTextField userIdTextField;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables
}
