/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.User;

import Business.Connection.Connection;
import Business.Network;
import Business.User.User;
import UserInterface.EmailPage;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author barua
 */
public class UserHomePage extends javax.swing.JPanel {

    /**
     * Creates new form UserHomePage
     */
    private JPanel userProcessContainer;
    private Network network;
    private User user;

    public UserHomePage(JPanel userProcessContainer, Network network, User user) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.network = network;
        this.user = user;
        displayDetails();
        getConnections();
    }

    public void displayDetails() {
        welcomeLabel.setText(user.getFullName());
        name_jlabel.setText(user.getFullName());
        SimpleDateFormat mdyFormat = new SimpleDateFormat("MM-dd-yyyy");
        Date myDate = user.getDateOfBirth();
        String formatedDate = mdyFormat.format(myDate);
        dateofBirth_jlabel.setText(formatedDate);
        gender_jlabel.setText(user.getGender());
        bloodGroup_jlabel.setText(user.getBloodGroup());
        ssn_jlabel.setText(user.getSocialSecurityNumber());
        email_jlabel.setText(user.getEmailId());
        contactNumber_jlabel.setText(user.getContactNumber());
        streetAddress_jlabel.setText(user.getAddress().getStreetAddress());
        city_jlabel.setText(user.getAddress().getCity());
        zipCode_jlabel.setText(user.getAddress().getZipCode());
        state_jlabel.setText(user.getAddress().getState());
        country_jlabel.setText(user.getAddress().getCountry());
    }

    public void getConnections() {
        DefaultTableModel defaultTableModel = (DefaultTableModel) userdetails_jTable.getModel();
        TableColumnModel tableColumnModel = userdetails_jTable.getColumnModel();
        defaultTableModel.setRowCount(0);
        for (Connection connection : network.getConnectionDirectory().getConnectionDirectory()) {
            if (connection.getSenderUser().getEmailId().equals(user.getEmailId())) {
                Object row[] = new Object[defaultTableModel.getColumnCount()];
                row[0] = connection.getRecieverUser();
                row[1] = connection.getRecieverUser().getBloodGroup();
                row[2] = connection.getRecieverUser().getAddress().getZipCode();
                row[3] = connection.getStatus();
                row[4] = connection;
                defaultTableModel.addRow(row);
            }
            if (connection.getRecieverUser().getEmailId().equals(user.getEmailId())) {
                Object row[] = new Object[defaultTableModel.getColumnCount()];
                row[0] = connection.getSenderUser();
                row[1] = connection.getSenderUser().getBloodGroup();
                row[2] = connection.getSenderUser().getAddress().getZipCode();
                row[3] = connection.getStatus();
                row[4] = connection;
                defaultTableModel.addRow(row);
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        upd_Prof = new javax.swing.JButton();
        srch_Blooddbank = new javax.swing.JButton();
        srch_Donar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        name_jlabel = new javax.swing.JLabel();
        dateofBirth_jlabel = new javax.swing.JLabel();
        gender_jlabel = new javax.swing.JLabel();
        bloodGroup_jlabel = new javax.swing.JLabel();
        ssn_jlabel = new javax.swing.JLabel();
        email_jlabel = new javax.swing.JLabel();
        contactNumber_jlabel = new javax.swing.JLabel();
        streetAddress_jlabel = new javax.swing.JLabel();
        city_jlabel = new javax.swing.JLabel();
        zipCode_jlabel = new javax.swing.JLabel();
        state_jlabel = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        country_jlabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userdetails_jTable = new javax.swing.JTable();
        contact_jButton = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        welcomeLabel = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        upd_Prof.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        upd_Prof.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/32/Knob-Upload-icon.png"))); // NOI18N
        upd_Prof.setText("Update Profile");
        upd_Prof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upd_ProfActionPerformed(evt);
            }
        });
        add(upd_Prof, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 185, 237, 50));

        srch_Blooddbank.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        srch_Blooddbank.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/32/Knob-Search-icon.png"))); // NOI18N
        srch_Blooddbank.setText("Search Blood Bank");
        srch_Blooddbank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srch_BlooddbankActionPerformed(evt);
            }
        });
        add(srch_Blooddbank, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 93, 237, 50));

        srch_Donar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        srch_Donar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/32/Knob-Search-icon.png"))); // NOI18N
        srch_Donar.setText("Search Donar");
        srch_Donar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srch_DonarActionPerformed(evt);
            }
        });
        add(srch_Donar, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 285, 237, 50));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Email:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 253, 138, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Gender:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 157, 138, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Date of Birth :");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 125, 138, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Name :");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 93, 138, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Social Security Number:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 221, 138, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Blood Group:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 189, 138, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Contact Number:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 285, 138, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Street Address:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 317, 138, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("City:");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 349, 138, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Zip Code:");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 381, 138, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("State:");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 413, 138, -1));

        name_jlabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add(name_jlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 93, 273, 14));

        dateofBirth_jlabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add(dateofBirth_jlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 125, 273, 14));

        gender_jlabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add(gender_jlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 157, 273, 14));

        bloodGroup_jlabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add(bloodGroup_jlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 189, 273, 14));

        ssn_jlabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add(ssn_jlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 221, 273, 14));

        email_jlabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add(email_jlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 253, 273, 14));

        contactNumber_jlabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add(contactNumber_jlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 285, 273, 14));

        streetAddress_jlabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add(streetAddress_jlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 317, 273, 14));

        city_jlabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add(city_jlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 349, 273, 14));

        zipCode_jlabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add(zipCode_jlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 381, 273, 14));

        state_jlabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add(state_jlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 413, 273, 14));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Country:");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 449, 138, -1));

        country_jlabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add(country_jlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 449, 273, 14));

        userdetails_jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Blood group", "Zip Code", "Status", "Hospital Status "
            }
        ));
        jScrollPane1.setViewportView(userdetails_jTable);
        if (userdetails_jTable.getColumnModel().getColumnCount() > 0) {
            userdetails_jTable.getColumnModel().getColumn(0).setResizable(false);
            userdetails_jTable.getColumnModel().getColumn(1).setResizable(false);
            userdetails_jTable.getColumnModel().getColumn(2).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(768, 113, 490, 242));

        contact_jButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        contact_jButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/16/Knob-Add-icon.png"))); // NOI18N
        contact_jButton.setText("Contact User");
        contact_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contact_jButtonActionPerformed(evt);
            }
        });
        add(contact_jButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(768, 373, -1, -1));

        back.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/32/Knob-Shuffle-On-icon.png"))); // NOI18N
        back.setText("View Request");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 381, 237, 50));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/16/Knob-Valid-Blue-icon.png"))); // NOI18N
        jButton1.setText("Approve Request");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 370, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/16/Knob-Cancel-icon.png"))); // NOI18N
        jButton2.setText("Block User");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 370, -1, -1));

        jLabel1.setFont(new java.awt.Font("Cambria", 3, 18)); // NOI18N
        jLabel1.setText("Your Connections ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(929, 68, -1, -1));

        jLabel2.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        jLabel2.setText("Welcome : ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 23, -1, -1));

        welcomeLabel.setFont(new java.awt.Font("Cambria", 3, 18)); // NOI18N
        add(welcomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 305, 27));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/16/Knob-Loop-Off-icon.png"))); // NOI18N
        jButton3.setText("Refresh ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 70, -1, -1));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/User/watermark_1.PNG"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 610));
    }// </editor-fold>//GEN-END:initComponents

    private void upd_ProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upd_ProfActionPerformed
        UpdateProfile update = new UpdateProfile(userProcessContainer, network, user);
        userProcessContainer.add("UpdateProfileJPanel", update);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_upd_ProfActionPerformed

    private void srch_BlooddbankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srch_BlooddbankActionPerformed
        SearchBloodBank srchbloodbnk = new SearchBloodBank(userProcessContainer, network, user);
        userProcessContainer.add("SearchBloodBankJPanel", srchbloodbnk);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_srch_BlooddbankActionPerformed

    private void srch_DonarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srch_DonarActionPerformed
        SearchBloodDonor srchbloodDnr = new SearchBloodDonor(userProcessContainer, network, user);
        userProcessContainer.add("SearchBloodBankJPanel", srchbloodDnr);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
// TODO add your handling code here:
    }//GEN-LAST:event_srch_DonarActionPerformed

    private void contact_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contact_jButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = userdetails_jTable.getSelectedRow();
        if (selectedRow >= 0) {
            User selectedUser = (User) userdetails_jTable.getValueAt(selectedRow, 0);
            Connection connection = (Connection) userdetails_jTable.getValueAt(selectedRow, 4);
            int token = 0;
            if ((connection.getSenderUser().getEmailId().equals(selectedUser.getEmailId()) && connection.getRecieverUser().getEmailId().equals(user.getEmailId())) || (connection.getSenderUser().getEmailId().equals(user.getEmailId()) && connection.getRecieverUser().getEmailId().equals(selectedUser.getEmailId()))) {
                if (connection.getStatus().equals("Connected")) {
                    String sendersEmail = user.getEmailId();
                    String receiversEmail = selectedUser.getEmailId();
                    EmailPage emailPage = new EmailPage(userProcessContainer, network, sendersEmail, receiversEmail);
                    userProcessContainer.add("emailPage", emailPage);
                    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                    layout.next(userProcessContainer);
                } else {
                    JOptionPane.showMessageDialog(null, "You are not allowed to contact this user as you are blocked");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row");
        }


    }//GEN-LAST:event_contact_jButtonActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        ViewRequest viewRequest = new ViewRequest(userProcessContainer, network, user);
        userProcessContainer.add("viewRequest", viewRequest);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = userdetails_jTable.getSelectedRow();
        if (selectedRow >= 0) {
            User selectedUser = (User) userdetails_jTable.getValueAt(selectedRow, 0);
            int token = 0;
            Connection connection = (Connection) userdetails_jTable.getValueAt(selectedRow, 4);
            if (connection.getSenderUser().getEmailId().equals(selectedUser.getEmailId()) && connection.getRecieverUser().getEmailId().equals(user.getEmailId()) && connection.getHospitalStatus().equals("Received") && connection.getStatus().equals("Pending")) {
                connection.setStatus("Connected");
                getConnections();
                token = 1;
            }
            if (token == 1) {
                JOptionPane.showMessageDialog(null, "Request Approved");
                getConnections();
            }
            if (token == 0) {
                JOptionPane.showMessageDialog(null, "You cannot approve this request");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int selectedRow = userdetails_jTable.getSelectedRow();
        int token = 0;
        if (selectedRow >= 0) {
            User selectedUser = (User) userdetails_jTable.getValueAt(selectedRow, 0);
            Connection connection = (Connection) userdetails_jTable.getValueAt(selectedRow, 4);
            if ((connection.getSenderUser().getEmailId().equals(selectedUser.getEmailId()) && connection.getRecieverUser().getEmailId().equals(user.getEmailId())) || (connection.getSenderUser().getEmailId().equals(user.getEmailId()) && connection.getRecieverUser().getEmailId().equals(selectedUser.getEmailId())) && connection.getHospitalStatus().equals("Received")) {
                if (connection.getStatus().equals("Blocked")) {
                    JOptionPane.showMessageDialog(null, "User is already blocked");
                } else {
                    token = 1;
                    connection.setStatus("Blocked");
                    JOptionPane.showMessageDialog(null, "User Blocked");
                    getConnections();
                }
            }
            if (token == 0) {
                JOptionPane.showMessageDialog(null, "You cannot block this user as this request. Please check connection status");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        getConnections();
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel bloodGroup_jlabel;
    private javax.swing.JLabel city_jlabel;
    private javax.swing.JLabel contactNumber_jlabel;
    private javax.swing.JButton contact_jButton;
    private javax.swing.JLabel country_jlabel;
    private javax.swing.JLabel dateofBirth_jlabel;
    private javax.swing.JLabel email_jlabel;
    private javax.swing.JLabel gender_jlabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel name_jlabel;
    private javax.swing.JButton srch_Blooddbank;
    private javax.swing.JButton srch_Donar;
    private javax.swing.JLabel ssn_jlabel;
    private javax.swing.JLabel state_jlabel;
    private javax.swing.JLabel streetAddress_jlabel;
    private javax.swing.JButton upd_Prof;
    private javax.swing.JTable userdetails_jTable;
    private javax.swing.JLabel welcomeLabel;
    private javax.swing.JLabel zipCode_jlabel;
    // End of variables declaration//GEN-END:variables
}
